### PR TITLE
Signup and Login functionality added

### PR DESCRIPTION
**Pull request by emlama**
Hey there, I saw that login and sign up functionality was sort of on the todo list for this plugin so I took a try. The plugin is smart and when it sees the path 'users' or 'login' it leaves them as the base otherwise it adds in the 'classes' prefix.

Hope this helps :)

### CODE REVIEW

**Comment by tikhon** [comment]
nice!

**Comment by srhyne** [comment]
Hi Matthew, 

Thank you for the fork. However, I took a step back and really changed the $.ajax request architecture a bit. Now, all non "classes/" resources work out of the box and GET requests always get their data form url encoded. 

**ONE BIG CHANGE.** Due to the changes I made `$.parse.get` queries must be done like this...

```
 $.parse.get('tasks', {
    where : {...}
  });
```

But it's actually a lot better this way because now you can pass limit, skip, order, etc to get.

**Comment by tikhon** [comment]
nice, makes sense

**Comment by emlama** [comment]
Yeah that makes a lot more sense. I didn't even know about the Parse 'where' requests until I got to that part in the plugin :)

**Pull request closed without merging**
